// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class PigeonFlavorPigeonCodecReader: FlutterStandardReader {
}

private class PigeonFlavorPigeonCodecWriter: FlutterStandardWriter {
}

private class PigeonFlavorPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonFlavorPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonFlavorPigeonCodecWriter(data: data)
  }
}

class PigeonFlavorPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonFlavorPigeonCodec(readerWriter: PigeonFlavorPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FlavorApi {
  func getFlavor() throws -> String
  func getAppName() throws -> String
  func isProd() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FlavorApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonFlavorPigeonCodec.shared }
  /// Sets up an instance of `FlavorApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FlavorApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getFlavorChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pigeon_flavor_package.FlavorApi.getFlavor\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getFlavorChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getFlavor()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getFlavorChannel.setMessageHandler(nil)
    }
    let getAppNameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pigeon_flavor_package.FlavorApi.getAppName\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAppNameChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getAppName()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getAppNameChannel.setMessageHandler(nil)
    }
    let isProdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.pigeon_flavor_package.FlavorApi.isProd\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isProdChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isProd()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isProdChannel.setMessageHandler(nil)
    }
  }
}
